# Generated by Django 3.2.19 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sci-fi', 'Sci-Fi'), ('animation', 'Animation')], db_index=True, default='action', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada')], db_index=True, default='english', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'language'], name='movies_movi_genre_08a05d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
    ]
