# Generated by Django 5.2.14 on 2026-06-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20260529_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='show_time',
            field=models.CharField(choices=[('10:00 AM', '10:00 AM - Morning Show'), ('01:00 PM', '01:00 PM - Afternoon Show'), ('04:00 PM', '04:00 PM - Evening Show'), ('07:00 PM', '07:00 PM - Night Show'), ('10:00 PM', '10:00 PM - Late Night Show')], db_index=True, default='07:00 PM', max_length=20),
        ),
    ]
