# Generated by Django 5.2.14 on 2026-06-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_theater_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='show_time',
        ),
    ]
