# Generated by Django 5.2.14 on 2026-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_theater_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='show_time',
            field=models.CharField(choices=[('10:00 AM', '10:00 AM - Morning Show'), ('01:00 PM', '01:00 PM - Afternoon Show'), ('04:00 PM', '04:00 PM - Evening Show'), ('07:00 PM', '07:00 PM - Night Show'), ('10:00 PM', '10:00 PM - Late Night Show')], db_index=True, default='07:00 PM', max_length=20),
        ),
    ]
