# Generated by Django 5.2.14 on 2026-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_booking_and_lock_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium Recliner'), ('gold', 'Executive Gold'), ('silver', 'Classic Silver')], db_index=True, default='silver', max_length=10),
        ),
    ]
