# Generated by Django 5.2.14 on 2026-06-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_seat_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
    ]
