# Generated by Django 5.2.14 on 2026-06-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_seat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('vip', 'VIP Lounge'), ('premium', 'Premium Recliner'), ('gold', 'Executive Gold'), ('silver', 'Classic Silver'), ('basic', 'Basic')], db_index=True, default='basic', max_length=10),
        ),
    ]
